services:
  - type: web
    name: investment-dashboard-backend
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'npm start'
    envVars:
      - key: PORT
        value: 3001
